openclimatefix/pv-site-datamodel

sdk/python/pvsite_datamodel/sqlmodels.py

Add 'created_utc` mixin
Fixes #17 
did not run test locally, waiting for #18 to be merged

add created mixin

---

sdk/python/pvsite_datamodel/read.py
sdk/python/pvsite_datamodel/write/generation.py
sdk/python/tests/test_read.py

add a function to read all sites
Fixes #14
added test to check read functions work

add read all sites function + tests #14

---

sdk/python/pvsite_datamodel/sqlmodels.py
sdk/python/requirements.txt
sdk/python/setup.py
sdk/python/tests/test_read.py

Updates for pv-site-production
Fixes #
added tests

Fix to use with pv site production

---

sdk/python/pvsite_datamodel/sqlmodels.py

add client relationship to site
Useful for https://github.com/openclimatefix/PVSiteAPI/issues/20
CI tests + tested locally on API code

add client relationship to site

---

sdk/python/scripts/add_dno.py
sdk/python/scripts/add_gsp.py
sdk/python/scripts/gsp_new_ids_and_names-edited.csv

Add script to add gsp and dno details into database. 
#58 
Ran this and changed the gsps and dnos in the dev database

add gsp details to sites

---

sdk/python/pvsite_datamodel/sqlmodels.py

This is why we should *systematically* use PRs and never merge to `main` directly!
Tests and lint were broken on `main`.

Fix tests and broken lint

---

README.md
pvsite_datamodel/__init__.py
pvsite_datamodel/read/__init__.py
pvsite_datamodel/read/user.py
scripts/add_all_sites_to_user.py
tests/test_read.py

- update readme
- add `get_site_group_by_name`
- add script to give access to all sites, if ocf member
- add tests
- other CI tests
- ran script locally

add get_site_group_by_name + tests #major

---

pvsite_datamodel/read/site.py
tests/test_read.py

- order sites when reading sites
Fixes #
- CI tests
- added to tests

make sure sites are ordered

---

pvsite_datamodel/pydantic_models.py
pvsite_datamodel/read/__init__.py
pvsite_datamodel/read/site.py
tests/conftest.py
tests/test_read.py

get sites from user, with lat and lon filter
Fixes #83 
Moved this from pv-site-api
CI tests

add get_sites_from_user function. +tests

---

README.md

This PR includes changes in the repo level README.md to include the pvsite database schema as a Mermaid diagram 
Diagrams rendered in Github repo homepage

Add PVSite database schema

---

pvsite_datamodel/read/latest_forecast_values.py

add contain_eagers to read, this speeds up sql query
Tested it locally + CI tsts

add container eager

---

pvsite_datamodel/read/latest_forecast_values.py

sorted by created desc also, when read latest forecast values
Fixes #
Ci tests

add order by created utc desc

---

pyproject.toml

Move geopandas to dev
Fixes #
CI tests

moved geopandas under dev.dependencies (#111)

---

pvsite_datamodel/__init__.py
pvsite_datamodel/read/__init__.py
pvsite_datamodel/read/user.py
tests/test_read.py

Add read api requests functions
Fixes #130
CI tests + new tests

add read and tests #130

---

pvsite_datamodel/write/database.py

Only get user, if we need to
CI tests

dont get user if its already there

---

pvsite_datamodel/pydantic_models.py
pvsite_datamodel/write/user_and_site.py
tests/test_write.py

This PR refers to the issue #144 : Create an edit_site function
Creation of the PVSiteEditMetadata pydantic model, with all Optional field, so you can update one or as many field as you want.
Creation of the edit_site function, and tests for it.
I tested via pytest, with different configuration : update a single field, more fields, set a field to None, etc. And made sure that unfilled field are not impacted.

Add a edit_site function (#144)

---

README.md

I edited the readme file to add the recently created edit_site function.
don't needed.

Edit REAMDE file to add edit_site function (#144)

---

.github/workflows/sdk-python-ci.yml

Include `synchronize` trigger so that workflows run on every commit to a PR.

add synchronize

---

pvsite_datamodel/write/user_and_site.py
tests/write/test_site.py

remove - site and site group
Helps with https://github.com/openclimatefix/analysis-dashboard/issues/292

add a remove site option + test

---

pvsite_datamodel/write/user_and_site.py
tests/write/test_site.py

new function to `set_site_to_inactive_if_not_in_site_group`
This is needed if users share a site, so they dont delete the site for others
Helps with https://github.com/openclimatefix/pv-site-api/issues/210

add set_site_to_inactive_if_not_in_site_group + tests

---

pvsite_datamodel/read/user.py

Make sure site is filter on email address
helps with https://github.com/openclimatefix/analysis-dashboard/issues/301
- CI tests
- tested locally with internal dashboard

add join and filter on email

---

pvsite_datamodel/write/generation.py

Fix for write generation. Allow both site_uuid and location_uuid columns
Ci tests

update write method for generation
